name: Checks
on: [push, pull_request]

jobs:
  lint:
    name: Ensure the code is formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: dprint check
  deploy-test:
    name: Verify the site can be deployed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      # I'm disabling gl for now
      # - name: Install gl dependencies
      # run: sudo apt-get install build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: Install npm dependencies
        run: npm ci --omit=optional

      - name: Install openscad
        run: sudo apt-get install -y openscad

      - name: Compile Code
        run: mkdir target && make

      # Disabled since Verel does this now, and I like the GitHub checks to be fast.
      # - name: Build keycaps
      #   run: |
      #     export OPENSCAD=$(which openscad)
      #     make keycaps-simple
      #     make keycaps

      - name: Build simple keycaps
        run: OPENSCAD=$(which openscad) make keycaps-simple

      - name: Build parts
        run: make parts parts-simple

      # Disabled since this requires the clojure parts to be built
      # - name: Build Parts
      #   run: make parts

      - name: Build site
        run: npm run build
