name: PR Checks
on: [push, pull_request]

jobs:
  lint:
    name: Ensure the code is formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: dprint check
